version: '3.4'

services:
  employeesdb:
    image: mariadb
    restart: always
    ports:
      - "3308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 97033
      MARIADB_DATABASE: employeesdb
      MARIADB_USER: root
    volumes:
      # persist data files into `datadir` volume managed by docker

      # bind-mount any sql files that should be run while initializing
      - ./init:/docker-entrypoint-initdb.d

  suggestionapp:
    image: ${DOCKER_REGISTRY-}suggestionapp
    build:
      context: .
      dockerfile: SuggestionApp/Dockerfile
    ports:
      - "55000:443"
    depends_on: 
     - employeesdb
  
  frontend:
    build: ../../SuggestionUI/NordicProjectFrontend
    ports:
      - "4200:80"